/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package winnipegtransit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Date;
import java.net.URL;
import java.net.MalformedURLException;
import org.json.JSONObject;
import org.json.JSONException;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;



/**
 *
 * @author owen
 */
public class TransitGUI extends javax.swing.JFrame {
    private StopInfo stopInfo;
    private Schedule schedule;
    private TransitConnection connection;  
    private String name;
    private String latitude;
    private String longitude;
    private Date queryDateTime;
    private Calendar calendar;
    private URL timeURL;
    private JSONObject timeJson;
    private long time;    
    private final String API_KEY = "api-key=bEUgnZTNurbZtGAnBnJT";
    private final String WT_URL = "http://api.winnipegtransit.com/";
    DateFormat dayAndTime = new SimpleDateFormat("EEE, MMM, d  - HH:mm");
    DateFormat tf = new SimpleDateFormat("HH:mm");

    /**
     * Creates new form TransitGUI
     */
    public TransitGUI() {
        initComponents();
        setTime();
    }
    
    private Date parseToDate(String dateString)
    {
        return javax.xml.bind.DatatypeConverter.parseDateTime(dateString).getTime();
        
        //PICK UP FROM HERE
    }
            
    private void setTime()
    {
        
        String dateString;
        
        try
        {
            timeURL = new URL(WT_URL + "/time.json?" + API_KEY);
            timeJson = retrieveFromWeb(timeURL);
            
            dateString = timeJson.getString("time");
            
            //calendar = javax.xml.bind.DatatypeConverter.parseDateTime(dateString);
            queryDateTime = parseToDate(dateString);
                    
            
            lblTime.setText(dayAndTime.format(queryDateTime));
            

                    
        }
        catch (MalformedURLException malx)
        {
            malx.printStackTrace();
        }
        catch (IOException iox)
        {
            tarSchedule.append("Could not connect to Winnipeg Transit service. Please check your internet connection.");
        }
        catch (NullPointerException nex)
        {
            //Null pointer will be thrown because there is no connection available. The message above will be displayed.
        }         
    }
    
    //pull this out into a seperate class so it can be used from both this cass and the transitConnection class.
    private JSONObject retrieveFromWeb(URL url)
    {
        BufferedReader in;
        String strLine;
        StringBuilder jsonInfo;
        jsonInfo = new StringBuilder();
        in = null;
        JSONObject toReturn = null;
       //read the stream from the URL into a buffered reader
        try
        {
            in = new BufferedReader(new InputStreamReader(url.openStream()));
            
            while ((strLine = in.readLine()) != null )
            {
                jsonInfo.append(strLine);
            }
            
            in.close();
        }
        catch (IOException iox)
        {
            System.out.println("\nInvalid stop number or connection unavailable. Please try again.");
        }
        
        try
        {

            toReturn  = new JSONObject(jsonInfo.toString());
        }
        catch (JSONException jex)
        {
            tarSchedule.setText("Could not connect to Winnipeg Transit Service. Please check your internet connection.");
        }
        
        return toReturn;

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        author = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblStopNo = new javax.swing.JLabel();
        txtStop = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarSchedule = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarFeatures = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        title.setText("Winnipeg Transit StopChecker");

        author.setText("Created By: Owen Peterson");

        lblStopNo.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        lblStopNo.setText("Enter Stop Number:");

        txtStop.setBackground(new java.awt.Color(255, 255, 255));
        txtStop.setToolTipText("");
        txtStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStopActionPerformed(evt);
            }
        });

        btnCheck.setText("Check!");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel1.setText("Stop Name:");

        lblName.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel2.setText("Latitude:");

        lblLongitude.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLongitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLatitude.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLatitude.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel3.setText("Longitude:");

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel4.setText("Stop Schedule:");

        tarSchedule.setColumns(20);
        tarSchedule.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        tarSchedule.setRows(5);
        jScrollPane1.setViewportView(tarSchedule);

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel5.setText("Stop Features:");

        tarFeatures.setColumns(20);
        tarFeatures.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        tarFeatures.setRows(5);
        jScrollPane2.setViewportView(tarFeatures);

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        jLabel6.setText("System Time:");

        lblTime.setFont(new java.awt.Font("Droid Sans", 0, 15)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(lblStopNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtStop, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCheck))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lblName.getAccessibleContext().setAccessibleName("lblName");
        lblLongitude.getAccessibleContext().setAccessibleName("lblLattitude");
        jLabel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(title)
                    .addComponent(author))
                .addGap(0, 170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(author)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStopActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        ScheduleItem si = null;
        ArrayList<ScheduleItem> scheduleItems;
        ArrayList<BusArrival> busArrivals;
        ArrayList<StopFeature> stopFeatures;
        String busName;
        Date arrivalTime;
        StopFeature currentFeature;
        String featureName;
        int featureCount;
        
        if (evt.getSource() == btnCheck)
        {
            try
            {
             
                setTime();
                
                tarSchedule.setText("Checking stop information. Please wait...\n");
                connection = new TransitConnection(this.txtStop.getText());
                stopInfo = connection.getStopInfo();
                schedule = connection.getScheduleInfo();
                scheduleItems = schedule.getScheduleItems();
                stopFeatures = connection.getStopFeatures();

                name = stopInfo.getName();
                latitude = stopInfo.getLatitude();
                longitude = stopInfo.getLongitude();
             
            
                lblName.setText(name);
                lblLatitude.setText(latitude);
                lblLongitude.setText(longitude);
                
                tarSchedule.setText("");                
             
                
                
                for (int i = 0; i < scheduleItems.size(); i++)
                {
                    si = scheduleItems.get(i);
                    busArrivals = si.getBusArrivals();
                    tarSchedule.append(si.getRouteName() + "\n");
                    tarSchedule.append("--------------------------------------------------\n");
                    
                    for (int j = 0; j < busArrivals.size(); j++)
                    {
                        busName = busArrivals.get(j).getBusName();
                        arrivalTime = busArrivals.get(j).getArrivalTime();
                        
                        tarSchedule.append(busName + " - " + tf.format(arrivalTime) + "\n");
                    }
                    
                    tarSchedule.append("\n");
                }
                
                if (stopFeatures.isEmpty())
                {
                     tarFeatures.setText("This stop has no special features.");       
                }
                else
                {
                    tarFeatures.setText("");                
                
                    for (int i = 0; i < stopFeatures.size(); i++)
                    {
                        currentFeature = stopFeatures.get(i);
                        featureName = currentFeature.getName();
                        featureCount = currentFeature.getCount();

                        if (featureCount > 1 && featureName.equals("Bench"))
                        {
                            featureName += "es";
                        }

                        tarFeatures.append(featureCount + " " + featureName + "\n");                    

                    }
                }
                
            }
            catch (JSONException jex)
            {
               
            }
            catch (NullPointerException nex)
            {
                tarSchedule.append("Invalid stop number. Please enter a new number.\n");
            }
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransitGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransitGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel author;
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStopNo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextArea tarFeatures;
    private javax.swing.JTextArea tarSchedule;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtStop;
    // End of variables declaration//GEN-END:variables
}
